### ISSUE TITLE
Switching app configuration to 'library' crashes Workspace-D

### ISSUE THREAD

**Issue by SrMordred** [Pure-D/code-d#142]
Window 10
DMD32 D Compiler v2.076.0

**Comment by WebFreak001** [comment]
error log? (help -> developer console)
dub.json + source to replicate the issue? It doesn't happen with a plain new project

**Comment by SrMordred** [comment]
I tried with new project and give me the same:

```
extensionHost.ts:335 [Extension Host] WorkspaceD ended with code 3221225477
extensionHost.ts:335 [Extension Host] provideHover
shell.ts:423 This socket has been ended by the other party: Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:294:12)
    at WorkspaceD.request (C:\Users\Patric\.vscode\extensions\webfreak.code-d-0.16.2\out\src\workspace-d.js:1040:29)
    at Promise (C:\Users\Patric\.vscode\extensions\webfreak.code-d-0.16.2\out\src\workspace-d.js:414:18)
    at WorkspaceD.provideHover (C:\Users\Patric\.vscode\extensions\webfreak.code-d-0.16.2\out\src\workspace-d.js:410:16)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:354512
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:63028
    at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:48235)
    at Object.t.asWinJsPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:62991)
    at e.provideHover (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:354466)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:365518
e.onUnexpectedError @ shell.ts:423
(anonymous) @ shell.ts:383
e.onUnexpectedExternalError @ errors.ts:125
t.onUnexpectedExternalError @ errors.ts:147
(anonymous) @ hover.ts:34
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
(anonymous) @ async.ts:360
done @ winjs.base.raw.js:1378
v @ winjs.base.raw.js:1224
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
e.resolveErr @ ipcRemoteCom.ts:111
f @ ipcRemoteCom.ts:203
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98

```

**Comment by WebFreak001** [comment]
fixed in serve-d version now, merged into master
