### ISSUE TITLE
Code Completion Issues

### ISSUE THREAD

**Issue by gnunn1** [Pure-D/code-d#15]
Started vscode and started typing before DCD was ready and things never recovered so re-started. Here's what was in the developer tools:

```
[Plugin Host] Initialized code-d
workbench.main.js:67 [Plugin Host] dub is ready
workbench.main.js:67 [Plugin Host] DScanner is ready
workbench.main.js:67 [Plugin Host] Dfmt is ready
workbench.main.js:67 [Plugin Host] provideHover
workbench.main.js:67 [Plugin Host] provideCompletionItems
workbench.main.js:91 TypeError: Cannot read property 'length' of null: TypeError: Cannot read property 'length' of null
    at /opt/visual-studio-code/resources/app/out/vs/workbench/node/pluginHostProcess.js:19:2756
    at Object.p [as _notify] (/opt/visual-studio-code/resources/app/out/vs/workbench/node/pluginHostProcess.js:5:2360)
    at Object.__dirname.undefined.L.enter (/opt/visual-studio-code/resources/app/out/vs/workbench/node/pluginHostProcess.js:5:5522)
    at __dirname.undefined.t.Class.define._run (/opt/visual-studio-code/resources/app/out/vs/workbench/node/pluginHostProcess.js:5:7348)
    at __dirname.undefined.t.Class.define._completed (/opt/visual-studio-code/resources/app/out/vs/workbench/node/pluginHostProcess.js:5:6789)
    at process._tickCallback (node.js:368:9)e.onUnexpectedError @ workbench.main.js:91
workbench.main.js:67 [Plugin Host] Array[6]
workbench.main.js:67 [Plugin Host] DCD is ready
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:38.029:server.d:main:78 Starting up...

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:38.029:server.d:loadConfiguredImportDirs:312 Loading configuration from /home/gnunn/.config/dcd/dcd.conf

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:38.250:first.d:visit:379 Could not resolve location of module 'ldc/intrinsics'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:38.322:first.d:visit:379 Could not resolve location of module 'gcc/builtins'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:38.915:server.d:main:114 Import directories:
    /usr/include/dlang/dmd
2016-01-07T15:50:38.915:server.d:main:120 41611 symbols cached.

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:38.915:server.d:main:121 Startup completed in 885.354 milliseconds.

workbench.main.js:67 [Plugin Host] provideCompletionItems
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:39.985:server.d:
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: main:207 Getting completions

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:39.986:first.d:visit:379 Could not resolve location of module 'gdk/Atom'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:39.986:first.d:visit:379 Could not resolve location of module 'gdk/Event'
2016-01-07T15:50:39.986:first.d:visit:379 Could not resolve location of module 'gio/Application'
2016-01-07T15:50:39.986:first.d:visit:379 Could not resolve location of module 'gio/Notification'
2016-01-07T15:50:39.986:first.d:visit:379 Could not resolve location of module 'glib/Util'
2016-01-07T15:50:39.986:first.d:visit:379 Could not resolve location of module 'gtk/Box'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:39.986:first.d:visit:379 Could not resolve location of module 'gtk/Button'
2016-01-07T15:50:39.986:first.d:visit:379 Could not resolve location of module 'gtk/Container'
2016-01-07T15:50:39.986:first.d:visit:379 Could not resolve location of module 'gtk/Clipboard'
2016-01-07T15:50:39.986:first.d:visit:379 Could not resolve location of module 'gtk/ComboBox'
2016-01-07T15:50:39.986:first.d:visit:379 Could not resolve location of module 'gtk/Dialog'
2016-01-07T15:50:39.986:first.d:visit:379 Could not resolve location of module 'gtk/Entry'
2016-01-07T15:50:39.986:first.d:visit:379 Could not resolve location of module 'gtk/Grid'
2016-01-07T15:50:39.986:first.d:visit:379 Could not resolve location of module 'gtk/Label'
2016-01-07T15:50:39.987:first.d:visit:379 Could not resolve location of module 'gtk/Main'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:39.987:first.d:visit:379 Could not resolve location of module 'gtk/Menu'
2016-01-07T15:50:39.987:first.d:visit:379 Could not resolve location of module 'gtk/MenuItem'
2016-01-07T15:50:39.987:first.d:visit:379 Could not resolve location of module 'gtk/Paned'
2016-01-07T15:50:39.987:first.d:visit:379 Could not resolve location of module 'gtk/Widget'
2016
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: -01-07T15:50:39.987:first.d:visit:379 Could not resolve location of module 'gtk/Window'
2016-01-07T15:50:39.987:first.d:visit:379 Could not resolve location of module 'gx/gtk/util'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:39.987:first.d:visit:379 Could not resolve location of module 'gx/i18n/l10n'
2016-01-07T15:50:39.987:first.d:visit:379 
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: Could not resolve location of module 'gx/util/array'
2016-01-07T15:50:39.987:first.d:visit:379 Could not resolve location of module 'gx/terminix/preferences'
2016-01-07T15:50:39.987:first.d:visit:379 Could not resolve location of module 'gx/terminix/terminal/terminal'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:39.993:server.d:main:245 Request processed in 8.03659 milliseconds

workbench.main.js:67 [Plugin Host] resolve
workbench.main.js:67 [Plugin Host] Array[8]
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:24 [uncaught exception]: TypeError: Cannot convert object to primitive valueonError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:24
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:27 TypeError: Cannot convert object to primitive value
    at new Error (native)
    at Client.trackException (/opt/visual-studio-code/resources/app/node_modules/applicationinsights/Library/Client.js:67:25)
    at e.log (file:////opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:90:22274)
    at t.handleEvent (file:////opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:45:31955)
    at t.e.publicLog (file:////opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:45:29133)
    at t.e.flushErrorBuffer (file:////opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:45:27142)
    at file:////opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:45:27002onError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"workers"%3A-1%2C"enablePerformance"…:27
/opt/visual-studio-code/resources/app/node_modules/applicationinsights/Library/Client.js:67 Uncaught TypeError: Cannot convert object to primitive value
workbench.main.js:67 [Plugin Host] provideCompletionItems
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:48.543:server.d:main:207 Getting completions

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:48.544:first.d:visit:379 Could not resolve location of module 'gdk/Atom'
2016-01-07T15:50:48.544:first.d:visit:379 Could not resolve location of module 'gdk/Event'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:48.544:first.d:visit:379 Could not resolve location of module 'gio/Application'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gio/Notification'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'glib/Util'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gtk/Box'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gtk/Button'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gtk/Container'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gtk/Clipboard'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gtk/ComboBox'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gtk/Dialog'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gtk/Entry'
2016-01-07T15:50:48.545:first.d:visit
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: :379 Could not resolve location of module 'gtk/Grid'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gtk/Label'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gtk/Main'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gtk/Menu'
2016-01-
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gtk/MenuItem'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gtk/Paned'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gtk/Widget'
2016-01
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: -07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gtk/Window'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gx/gtk/util'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gx/i18n/l10n'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gx/util/array'
2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gx/terminix/preferences'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:48.545:first.d:visit:379 Could not resolve location of module 'gx/terminix/terminal/terminal'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:48.547:server.d:main:245 Request processed in 3.41144 milliseconds

workbench.main.js:67 [Plugin Host] resolve
workbench.main.js:67 [Plugin Host] Array[2]
workbench.main.js:67 [Plugin Host] provideCompletionItems
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:50.287:server.d:main:207 Getting completions

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gdk/Atom'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gdk/Event'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gio/Application'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gio/Notification'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'glib/Util'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/Box'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/Button'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/Container'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/Clipboard'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/ComboBox'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/Dialog'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/Entry'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/Grid'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/Label'
2016-01-07T15
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: :50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/Main'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/Menu'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/MenuItem'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/Paned'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/Widget'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gtk/Window'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gx/gtk/util'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gx/i18n/l10n'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gx/util/array'
2016-01-07T15:50:50.288:first.d:visit:379 Could not resolve location of module 'gx/terminix/preferences'
2016-01-07T15:50:50.289:first.d:visit:379 Could not resolve location of module 'gx/terminix/terminal/terminal'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:50.291:server.d:main:245 Request processed in 3.57429 milliseconds

workbench.main.js:67 [Plugin Host] resolve
workbench.main.js:67 [Plugin Host] Array[8]
workbench.main.js:67 [Plugin Host] provideSignatureHelp
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:51.863:server.d:main:207 Getting completions

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:51.864:server.d:main:245 Request processed in 0.684132 milliseconds

workbench.main.js:67 [Plugin Host] resolve null
workbench.main.js:67 [Plugin Host] provideCompletionItems
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:52.521:server.d:main:207 Getting completions

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gdk/Atom'
2016-01-
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gdk/Event'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gio/Application'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gio/Notification'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'glib/Util'
2016-01-07T15:50:52.
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 522:first.d:visit:379 Could not resolve location of module 'gtk/Box'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gtk/Button'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gtk/Container'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gtk/Clipboard'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gtk/ComboBox'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gtk/Dialog'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gtk/Entry'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gtk/Grid'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gtk/Label'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gtk/Main'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gtk/Menu'
2016-01-07T15:50:52.522:first.d:visit:379 
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: Could not resolve location of module 'gtk/MenuItem'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gtk/Paned'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gtk/Widget'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gtk/Window'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gx/gtk/util'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gx/i18n/l10n'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gx/util/array'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gx/terminix/preferences'
2016-01-07T15:50:52.522:first.d:visit:379 Could not resolve location of module 'gx/terminix/terminal/terminal'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:52.524:server.d:main:245 Request processed in 2.96547 milliseconds

workbench.main.js:67 [Plugin Host] resolve
workbench.main.js:67 [Plugin Host] Array[16]
workbench.main.js:67 [Plugin Host] provideCompletionItems
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:54.040:server.d:main:207 Getting completions

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:54.041:first.d:visit:379 Could not resolve location of module 'gdk/Atom'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:54.041:first.d:visit:379 Could not resolve location of module 'gdk/Event'
2016-01-07T15:50:54.041:first.d:visit:379 Could not resolve location of module 'gio/Application'
2016-01-07T15:50:54.041:first.d:visit:379 Could not resolve location of module 'gio/Notification'
2016-01-07T15:50:54.041:first.d:visit:379 Could not resolve location of module 'glib/Util'
2016-01-07T15:50:54.041:first.d:visit:379 Could not resolve location of module 'gtk/Box'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:54.041:first.d:visit:379 Could not resolve location of module 'gtk/Button'
2016-01-07T15:50:
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 54.041:first.d:visit:379 Could not resolve location of module 'gtk/Container'
2016-01-07T15:50:54.041:first.d:visit:379 Could not resolve location of module 'gtk/Clipboard'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:54.042:first.d:visit:379 Could not resolve location of module 'gtk/ComboBox'
2016-01-07T15:
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 50:54.042:first.d:visit:379 Could not resolve location of module 'gtk/Dialog'
2016-01-07T15:50:54.042:first.d:visit:379
workbench.main.js:67 [Plugin Host] WorkspaceD Debug:  Could not resolve location of module 'gtk/Entry'
2016-01-07T15:50:54.042:first.d:visit:379 Could not resolve location of module 'gtk/Grid'
2016-01-07T15:50:54.042:first.d:visit:379 Could not resolve location of module 'gtk/Label'
2016-01-07T15:50:54.042:first.d:visit:379 Could not resolve location of module 'gtk/Main'
2016-01-07T15:50:54.042:first.d:visit:379 Could not resolve location of module 'gtk/Menu'
2016-01-07T15:50:54.042:
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: first.d:visit:379 Could not resolve location of module 'gtk/MenuItem'
2016-01-07T15:50:54.042:first.d:visit:379 Could not resolve location of module 'gtk/Paned'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:54.042:first.d:visit:379 Could not resolve location of module 'gtk/Widget'
2016-0
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 1-07T15:50:54.042:first.d:visit:379 Could not resolve location of module 'gtk/Window'
2016-01-07T15:50:54.042:first.d:visit:379 
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: Could not resolve location of module 'gx/gtk/util'
2016-01-07T15:50:54.042:first.d:visit:379 Could not resolve location of module 'gx/i18n/l10n'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:54.042:first.d:visit:379 Could not resolve location of module 'gx/util/array'
2016-01-07T15
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: :50:54.042:first.d:visit:379 Could not resolve location of module 'gx/terminix/preferences'
2016-01-07T15:50:54.042:first.d:visit:379 Could not resolve location of module 'gx/terminix/terminal/terminal'

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:54.044:server.d:main:245 Request processed in 3.91932 milliseconds

workbench.main.js:67 [Plugin Host] resolve
workbench.main.js:67 [Plugin Host] Array[10]
workbench.main.js:67 [Plugin Host] provideSignatureHelp
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:55.436:server.d:main:207 Getting completions

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:55.436:server.d:main:245 Request processed in 0.566972 milliseconds

workbench.main.js:67 [Plugin Host] resolve null
workbench.main.js:67 [Plugin Host] provideCompletionItems
workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:56.048:server.d:main:207 Getting completions

workbench.main.js:67 [Plugin Host] WorkspaceD Debug: 2016-01-07T15:50:56.049:first.d:visit:379 Could not resolve location of module 'gdk/Atom'
2016-01-07T15:50:56
```

**Comment by WebFreak001** [comment]
Can you get workspace-d v2.0.0 and try again?

**Comment by gnunn1** [comment]
OK did a git pull for workspace-d and rebuilt it and then attempted to duplicate the issue but it worked fine. Closing the issue, thanks.
