### ISSUE TITLE
Code-d fails to initialize

### ISSUE THREAD

**Issue by mario-tripaneer** [Pure-D/code-d#181]
Heya, 

Since a few days ago code-d started failing to initialize, seems like it is trying to use dub even tho i have the setting : "d.neverUseDub": true

On the console log i see the following errors : 

`Could not initialize dub. Falling back to limited functionality!
e.onDidNotificationChange @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2217

4/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:260 
[Extension Host] rejected promise not handled within 1 second
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:260
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2870 

[webfreak.code-d]Dub isn't initialized yet
e.$onExtensionRuntimeError @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2870

/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2870 
Error: Dub isn't initialized yet
	at new ResponseError (/home/mario/.vscode/extensions/webfreak.code-d-0.17.2/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
	at handleResponse (/home/mario/.vscode/extensions/webfreak.code-d-0.17.2/node_modules/vscode-jsonrpc/lib/main.js:430:48)
	at processMessageQueue (/home/mario/.vscode/extensions/webfreak.code-d-0.17.2/node_modules/vscode-jsonrpc/lib/main.js:258:17)
	at Immediate.<anonymous> (/home/mario/.vscode/extensions/webfreak.code-d-0.17.2/node_modules/vscode-jsonrpc/lib/main.js:242:13)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)`

**Comment by WebFreak001** [comment]
do you have the latest serve-d yet? Try setting the beta stream setting to true so that it builds the latest commit.

**Comment by mario-tripaneer** [comment]
Sure, setting the beta stream results in this error : 
`[webfreak.code-d]Cannot read property 'author' of undefined`

**Comment by WebFreak001** [comment]
![wat](https://i.imgur.com/IppKJ.jpg)

**Comment by mario-tripaneer** [comment]
Alright, I see. :+1: let me know how it goes and when i should test it out again
Thanks for looking into it!

**Comment by WebFreak001** [comment]
now dub doesn't fatally crash serve-d anymore
