### ISSUE TITLE
code-d build/run project command not working: '' Error: command 'code-d.run' not found

### ISSUE THREAD

**Issue by dangbinghoo** [Pure-D/code-d#210]
Code-d is not working with recent VS Code for a long time: command 'code-d.xxx' not found.
OS: Archlinux 64bit
VS Code Version: 1.27.1

code-d versoin: 0.19.0
D language utility extension pack version: 0.3.0

the detailed error reported by developer tool console:

`notificationsAlerts.ts:39 Error: command 'code-d.run' not found 
    at t._tryExecuteCommand (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:3019:717)
    at file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:3019:572
    at Object.g [as _notify] (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:154:729)
    at Object.enter (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:158:61)
    at n.Class.derive._oncancel._run (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:159:902)
    at n.Class.derive._oncancel._completed (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:159:343)
    at l (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:162:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:163:45)
    at Object.g [as _notify] (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:154:729)
    at Object.enter (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:158:61)
    at n.Class.derive._oncancel._run (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:159:902)
    at n.Class.derive._oncancel._completed (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:159:343)
    at l (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:162:855)
    at n.Class.derive.join.r.forEach.j.then.o.(anonymous function) (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:163:45)
    at Object.g [as _notify] (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:154:729)
    at Object.enter (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:158:61)
    at n.Class.derive._creator._run (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:159:902)
    at n.Class.derive._creator._completed (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:159:343)
    at Object.g [as _notify] (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:154:729)
    at Object.enter (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:158:61)
    at n.Class.derive._oncancel._run (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:159:902)
    at n.Class.derive._oncancel._completed (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:159:343)
    at e.resolveOk (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:3166:685)
    at e._receiveReply (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:3234:965)
    at e._receiveOneMessage (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:3233:519)
    at file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:3232:74
    at e.fire (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:175:76)
    at a (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:311:740)
    at Socket.n._socketDataListener (file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:311:959)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)`

The same error exists for windows 10 either. And the situation has been like this for a very long period (at least 3 month).

will it be fixed?

**Comment by WebFreak001** [comment]
#208 #197

**Comment by dangbinghoo** [comment]
ok, thanks for your great work! I should take more attention on ChangeLog.
And, it might help more if you update the plugin README for describe some thing like `CTRL + SHIFT + B to build and run, debug directly using VS Code's debug`.

**Comment by WebFreak001** [comment]
Well that feature was rather a hack because vscode didn't support these things properly back then (it still doesn't do to an extent I want, but that will eventually be fixed I hope), it is just a bug that the commands are still present in the currently published version. This is fixed in master.

I think adding it to the README would be a good idea to show that the feature exists.
