### ISSUE TITLE
Code completion fails first time

### ISSUE THREAD

**Issue by gnunn1** [Pure-D/code-d#30]
When I'm using code-d I'm finding the code completion/hover always fails the first time with the error "Could not resolve location of module" however if I run the command to reload import paths it works fine after that. It's a minor nuisance but wanted to make sure it got captured as an issue. If posted output from the developer tools log below.

```
Plugin Host] Initialized code-d
workbench.main.js:88 [Plugin Host] dub is ready
workbench.main.js:88 [Plugin Host] DScanner is ready
workbench.main.js:88 [Plugin Host] Dfmt is ready
workbench.main.js:88 [Plugin Host] DlangUI is ready
workbench.main.js:88 [Plugin Host] ["/home/gnunn/Development/dlang/terminix/source/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/srcgstreamer/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/src/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/srcgl/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/srcsv/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/srcvte/"]
workbench.main.js:88 [Plugin Host] DCD is ready
workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:43:52.048:server.d:main:122 Starting up...

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:43:52.048:server.d:loadConfiguredImportDirs:377 Loading configuration from /home/gnunn/.config/dcd/dcd.conf
2016-02-10T12:43:52.048:server.d:main:156 Listening at /run/user/1000/dcd.socket

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:43:52.221:first.d:visit:379 Could not resolve location of module 'ldc/intrinsics'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:43:52.295:first.d:visit:379 Could not resolve location of module 'gcc/builtins'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:43:53.089:server.d:main:173 Import directories:
    /usr/include/dlang/dmd
2016-02-10T12:43:53.089:server.d:main:179 24465 symbols cached.

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:43:53.089:server.d:main:180 Startup completed in 1041.29 milliseconds.

workbench.main.js:88 [Plugin Host] provideHover
workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.418:server.d:main:279 Getting doc comment

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'cairo/Context'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'cairo/Surface'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gdk/Atom'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gdk/Cairo'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gdk/DragContext'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gdk/Event'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gdk/RGBA'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gdk/Screen'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gdkpixbuf/Pixbuf'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gio/ActionMapIF'
2016-02-10T12:44:01.420:first.d:visit:458 Could not reslove location of module 'gio/Menu'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.420:first.d:visit:458 Could not reslove location of module 'gio/MenuItem'
2016-02-10T12:44:01.420:first.d:visit:458 Could not reslove location of module 'gio/Settings'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gio/SimpleAction'
2016-0
workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gio/SimpleActionGroup'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gio/ThemedIcon'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'glib/GException'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'glib/Regex'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'glib/ShellUtils'
2016-02-10T12:44:01.420:first.d:visit:379
workbench.main.js:88 [Plugin Host] WorkspaceD Debug:  Could not resolve location of module 'glib/SimpleXML'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'glib/Str'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'glib/URI'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.420:first.d:visit:458 Could not reslove location of module 'glib/Variant'
2016-02-10T12:44:01.420:first.d:visit:458 Could not reslove location of module 'glib/VariantType'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gtk/Box'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gtk/Button'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gtk/Clipboard'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gtk/Dialog'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gtk/DragAndDrop'
2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gtk/EventBox'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gtk/Frame'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.420:first.d:visit:379 Could not resolve location of module 'gtk/Image'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/InfoBar'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/Label'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/Main'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/Menu'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/MenuButton'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/MenuItem'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/MessageDialog'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/MountOperation'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/Overlay'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/Popover'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/Revealer'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/Scrollbar'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/SelectionData'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/Separator'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/SeparatorMenuItem'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/TargetEntry'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gtk/Widget'
2016-02-10T12:44:01.421:first.d:visit:
workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 379 Could not resolve location of module 'gtk/Window'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'pango/PgFontDescription'
2016-02-10T12:44:01.421:first.d:visit:458 Could not reslove location of module 'vte/Terminal'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'vtec/vtetypes'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gx/gtk/actions'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gx/gtk/cairo'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gx/gtk/util'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gx/i18n/l10n'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gx/util/array'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gx/terminix/application'
2016
workbench.main.js:88 [Plugin Host] WorkspaceD Debug: -02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gx/terminix/cmdparams'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gx/terminix/common'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gx/terminix/constants'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gx/terminix/encoding'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gx/terminix/preferences'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gx/terminix/terminal/actions'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gx/terminix/terminal/search'
2016-02-10T12:44:01.421:first.d:visit:379 Could not resolve location of module 'gx/terminix/terminal/vtenotification'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.424:autocomplete.d:getDoc:67 Could not find symbol

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.429:server.d:main:310 Request processed in 11.3572 milliseconds

workbench.main.js:88 [Plugin Host] resolve null
workbench.main.js:88 [Plugin Host] provideHover
workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.622:server.d:main:279 Getting doc comment

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.624:first.d:visit:379 Could not resolve location of module 'cairo/Context'
2016-02-10T12:44:01.624:first.d:visit:379 Could not resolve location of module 'cairo/Surface'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.624:first.d:visit:379 Could not resolve location of module 'gdk/Atom'
2016-02-10T12:44:01.624:first.d:visit:379 Could not resolve location of module 'gdk/Cairo'
2016-02-10T12:44:01.624:first.d:visit:379 Could not resolve location of module 'gdk/DragContext'
2016-02-10T12:44:01.624:first.d:visit:379 Could not resolve location of module 'gdk/Event'
2016-02-10T12:44:01.624:first.d:visit:379 Could not resolve location of module 'gdk/RGBA'
2016-02-10T12:44:01.624:first.d:visit:379 Could not resolve location of module 'gdk/Screen'
2016-02-10T12:44:01.624:first.d:visit:379 Could not resolve location of module 'gdkpixbuf/Pixbuf'
2016-02-10T12:44:01.624:first.d:visit:379 Could not resolve location of module 'gio/ActionMapIF'
2016-02-10T12:44:01.624:first.d:visit:458 Could not reslove location of module 'gio/Menu'
2016-02-10T12:44:01.624:first.d:visit:458 Could not reslove location of module 'gio/MenuItem'
2016-02-10T12:44:01.624:first.d:visit:458 Could not reslove location of module 'gio/Settings'
2016-02-10T12:44:01.624:first.d:visit:379 Could not resolve location of module 'gio/SimpleAction'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gio/SimpleActionGroup'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gio/ThemedIcon'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'glib/GException'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'glib/Regex'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'glib/ShellUtils'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'glib/SimpleXML'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'glib/Str'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'glib/URI'
2016-02-10T12:44:01.625:first.d:visit:458 Could not reslove location of module 'glib/Variant'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.625:first.d:visit:458 Could not reslove location of module 'glib/VariantType'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Box'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Button'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Clipboard'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Dialog'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/DragAndDrop'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/EventBox'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Frame'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Image'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/InfoBar'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Label'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Main'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Menu'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/MenuButton'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/MenuItem'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/MessageDialog'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/MountOperation'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Overlay'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Popover'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Revealer'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Scrollbar'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/SelectionData'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Separator'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/SeparatorMenuItem'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/TargetEntry'
2016-02-10T12:44:01.625:first.d:visit:379 Could not resolve location of module 'gtk/Widget'
2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gtk/Window'
2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'pango/PgFontDescription'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.626:first.d:visit:458 Could not reslove location of module 'vte/Terminal'
2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'vtec/vtetypes'
2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gx/gtk/actions'
2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gx/gtk/cairo'
2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gx/gtk/util'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gx/i18n/l10n'
2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gx/util/array'
2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gx/terminix/application'
2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gx/terminix/cmdparams'
2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gx/terminix/common'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gx/terminix/constants'
2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gx/terminix/encoding'
2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gx/terminix/preferences'
2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gx/terminix/terminal/actions'
2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gx/terminix/terminal/search'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.626:first.d:visit:379 Could not resolve location of module 'gx/terminix/terminal/vtenotification'

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.628:autocomplete.d:getDoc:67 Could not find symbol

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:44:01.628:server.d:main:310 Request processed in 6.01107 milliseconds

workbench.main.js:88 [Plugin Host] resolve null
workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:46:00.559:modulecache.d:existanceCheck:60 Cannot cache modules in /usr/include/dmd/druntime/import because it does not exist
2016-02-10T12:46:00.559:modulecache.d:existanceCheck:60 Cannot cache modules in /usr/include/dmd/phobos because it does not exist

workbench.main.js:88 [Plugin Host] ["/home/gnunn/Development/dlang/terminix/source/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/srcgstreamer/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/src/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/srcgl/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/srcsv/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/srcvte/"]
workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:46:02.381:server.d:main:310 Request processed in 1822.11 milliseconds

workbench.main.js:88 [Plugin Host] provideHover
workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:46:06.035:server.d:main:279 Getting doc comment

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:46:06.049:autocomplete.d:getDoc:67 Could not find symbol

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:46:06.049:server.d:main:310 Request processed in 14.3994 milliseconds

workbench.main.js:88 [Plugin Host] resolve null
workbench.main.js:88 [Plugin Host] provideHover
workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:46:09.999:server.d:main:279 Getting doc comment

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:46:10.014:autocomplete.d:getDoc:67 Could not find symbol

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:46:10.014:server.d:main:310 Request processed in 15.1541 milliseconds

workbench.main.js:88 [Plugin Host] resolve null
workbench.main.js:88 [Plugin Host] provideHover
workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:46:10.469:server.d:main:279 Getting doc comment

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:46:10.488:autocomplete.d:getDoc:67 Could not find symbol

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:46:10.488:server.d:main:310 Request processed in 19.1509 milliseconds

workbench.main.js:88 [Plugin Host] resolve null
workbench.main.js:88 [Plugin Host] provideHover
workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:46:10.761:server.d:main:279 Getting doc comment

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:46:10.778:autocomplete.d:getDoc:67 Could not find symbol

workbench.main.js:88 [Plugin Host] WorkspaceD Debug: 2016-02-10T12:46:10.778:server.d:main:310 Request processed in 16.4049 milliseconds

workbench.main.js:88 [Plugin Host] resolve null
```

**Comment by WebFreak001** [comment]
oh i think it tries to load the paths before the server is running

**Comment by WebFreak001** [comment]
I would love to push the fix but since ive updated vscode it can't find the vscode module anymore

**Comment by WebFreak001** [comment]
Requires workspace-d update

**Comment by gnunn1** [comment]
I updated workspace-d but now I'm getting the following in the log:

```
[Plugin Host] Initialized code-d
workbench.main.js:88 [Plugin Host] dub is ready
workbench.main.js:88 [Plugin Host] DScanner is ready
workbench.main.js:88 [Plugin Host] Dfmt is ready
workbench.main.js:88 [Plugin Host] DlangUI is ready
workbench.main.js:88 [Plugin Host] ["/home/gnunn/Development/dlang/terminix/source/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/srcgstreamer/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/src/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/srcgl/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/srcsv/", "/home/gnunn/.dub/packages/gtk-d-3.2.2/srcvte/"]
3workbench.main.js:88 [Plugin Host] provideHover
workbench.main.js:88 [Plugin Host] provideCompletionItems
workbench.main.js:110 Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at file:////opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:68:23327
    at Object.h [as _notify] (file:////opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:23:26635)
    at Object.n.undefined.O.enter (file:////opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:23:29797)
    at n.undefined.t.Class.define._run (file:////opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:23:31623)
    at n.undefined.t.Class.define._completed (file:////opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:23:31064)
    at Object.h.handle (file:////opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:56:29131)
    at file:////opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:88:20404
    at ChildProcess.<anonymous> (file:////opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:88:23041)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
```

**Comment by gnunn1** [comment]
Also, no "DCD is ready" is appearing?

**Comment by gnunn1** [comment]
Never mind, think I had a stale dcd-server running. After killing it and re-starting it is working now. Thanks
