### ISSUE TITLE
Keep getting failed requests to server.

### ISSUE THREAD

**Issue by willdoescode** [Pure-D/code-d#357]
This happens seemingly at random, when I am importing anything, writing a return, writing a function.

If you are experiencing crashes, abnormal behaviour, etc. please open the Output panel in vscode and open the `code-d & serve-d` output. Please copy this log in a code block into this issue like this:

```
Error: Connection got disposed.
    at Object.dispose (/Users/willlane/.vscode/extensions/webfreak.code-d-0.22.0/node_modules/vscode-jsonrpc/lib/main.js:902:25)
    at Object.dispose (/Users/willlane/.vscode/extensions/webfreak.code-d-0.22.0/node_modules/vscode-languageclient/lib/client.js:74:35)
    at LanguageClient.handleConnectionClosed (/Users/willlane/.vscode/extensions/webfreak.code-d-0.22.0/node_modules/vscode-languageclient/lib/client.js:2236:42)
    at LanguageClient.handleConnectionClosed (/Users/willlane/.vscode/extensions/webfreak.code-d-0.22.0/node_modules/vscode-languageclient/lib/main.js:154:15)
    at closeHandler (/Users/willlane/.vscode/extensions/webfreak.code-d-0.22.0/node_modules/vscode-languageclient/lib/client.js:2223:18)
    at CallbackList.invoke (/Users/willlane/.vscode/extensions/webfreak.code-d-0.22.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/willlane/.vscode/extensions/webfreak.code-d-0.22.0/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/Users/willlane/.vscode/extensions/webfreak.code-d-0.22.0/node_modules/vscode-jsonrpc/lib/main.js:238:26)
    at CallbackList.invoke (/Users/willlane/.vscode/extensions/webfreak.code-d-0.22.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/willlane/.vscode/extensions/webfreak.code-d-0.22.0/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at StreamMessageReader.fireClose (/Users/willlane/.vscode/extensions/webfreak.code-d-0.22.0/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.<anonymous> (/Users/willlane/.vscode/extensions/webfreak.code-d-0.22.0/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12
```

**Comment by willdoescode** [comment]
I compiled code-d from source and im not getting these errors anymore
