### ISSUE TITLE
Parameters hints doesn't trigger if function has no documentation

### ISSUE THREAD

**Issue by RUSShyTwo** [Pure-D/code-d#381]
Code-D: v0.23.0
VSCode: 1.62.3

```D
void pass(int a, float b, string c)
{}

/// a documentation
void pass_doc(int a, float b, string c)
{}


void test()
{        ------- no parameters hints
    pass(|);
             --------- parameters hints show up
    pass_doc(|);
}
```

One guess: you probably check for documentation's length instead of the parameters hints list's length

**Comment by andy-hanson** [comment]
When typing the `(` for a function call, if you look in `Log (Window)`, there was a `TypeError`:

```
[2021-12-03 23:08:07.774] [renderer1] [error] Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asDocumentation (/home/andy/.vscode-oss/extensions/webfreak.code-d-0.23.2/node_modules/vscode-languageclient/lib/common/protocolConverter.js:170:27)
	at asSignatureInformation (/home/andy/.vscode-oss/extensions/webfreak.code-d-0.23.2/node_modules/vscode-languageclient/lib/common/protocolConverter.js:376:36)
	at Array.map (<anonymous>)
	at asSignatureInformations (/home/andy/.vscode-oss/extensions/webfreak.code-d-0.23.2/node_modules/vscode-languageclient/lib/common/protocolConverter.js:371:22)
	at asSignatureHelp (/home/andy/.vscode-oss/extensions/webfreak.code-d-0.23.2/node_modules/vscode-languageclient/lib/common/protocolConverter.js:366:33)
	at async W.provideSignatureHelp (/home/andy/bin/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:184932)
```

**Comment by WebFreak001** [comment]
@andy-hanson thanks for that tip! Turns out I was missing a few `mixin StrictOptionalSerializer` in the serve-d protocol definition, which is needed to make painlessjson not emit Optional!T.init at all (instead of emitting null) - a little hacky but works well with painlessjson. Might want to switch to something else in the future though, like asdf or mir-ion

A few other things related to calltips actually work better now as well, now that I properly made the undefined values not emit.
