### ISSUE TITLE
Cannot set properties of undefined (setting 'served')

### ISSUE THREAD

**Issue by Jeffrey-de-Bruijn** [Pure-D/code-d#419]
1. Installed official VSCode on RHEL9 with RPM
2. Installed official DMD with RPM
3. Installed code-d

When activated for the first time, code-d told me it couldn't find serve-d, so it installed the following executables in the local user directory
```bash
ls -lah ~/.local/share/code-d/bin/
total 15M
drwxrwxr-x. 2 jdb jdb   57 Jul 19 18:15 .
drwxrwxr-x. 3 jdb jdb   17 Jul 19 18:15 ..
-rwxr-xr-x. 1 jdb jdb 1.9M Jul 16  2021 dcd-client
-rwxr-xr-x. 1 jdb jdb 3.6M Jul 16  2021 dcd-server
-rwxr-xr-x. 1 jdb jdb 9.6M Jan  7  2022 serve-d
```

Now the following error still shows up: `Cannot set properties of undefined (setting 'served')`

There is no "served" setting in settings.json, only the following
```
"d.dubCompiler": "dmd",
"d.stdlibPath": "auto",
"d.dubPath": "/home/jdb/.local/bin/dub",
"d.servedPath": "/home/jdb/.local/share/code-d/bin/serve-d"
```

**Comment by WebFreak001** [comment]
do you maybe have the full code-d output log from the vscode output tab? (dropdown: code-d & serve-d log)

**Comment by Richardn2002** [comment]
I encountered the same problem, so I will attach the log related:

```
2023-12-21 14:40:18.375 [error] TypeError: Cannot set properties of undefined (setting 'served')
	at linkDebuggersWithServed (/home/richardn/.vscode-oss/extensions/webfreak.code-d-0.23.2-universal/out/debug.js:30:26)
	at startClient (/home/richardn/.vscode-oss/extensions/webfreak.code-d-0.23.2-universal/out/extension.js:289:41)
	at /home/richardn/.vscode-oss/extensions/webfreak.code-d-0.23.2-universal/out/extension.js:640:13
	at Generator.next (<anonymous>)
	at fulfilled (/home/richardn/.vscode-oss/extensions/webfreak.code-d-0.23.2-universal/out/extension.js:5:58)
```

**Comment by Richardn2002** [comment]
Yeah by reading the source, one of `webfreak.debug` `ms-vscode.cpptools` or `vadimcn.vscode-lldb` must be enabled for the plugin to work. After enabling the LLDB plugin this error goes away, still, I am facing one remaining error:

```
2023-12-21 15:56:38.842 [error] Error: Connection to server got closed. Server will not be restarted.
	at LanguageClient.handleConnectionClosed (/home/richardn/.vscode-oss/extensions/webfreak.code-d-0.23.2-universal/node_modules/vscode-languageclient/lib/common/client.js:2512:47)
	at LanguageClient.handleConnectionClosed (/home/richardn/.vscode-oss/extensions/webfreak.code-d-0.23.2-universal/node_modules/vscode-languageclient/lib/node/main.js:159:15)
	at closeHandler (/home/richardn/.vscode-oss/extensions/webfreak.code-d-0.23.2-universal/node_modules/vscode-languageclient/lib/common/client.js:2479:18)
	at CallbackList.invoke (/home/richardn/.vscode-oss/extensions/webfreak.code-d-0.23.2-universal/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/richardn/.vscode-oss/extensions/webfreak.code-d-0.23.2-universal/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/home/richardn/.vscode-oss/extensions/webfreak.code-d-0.23.2-universal/node_modules/vscode-jsonrpc/lib/common/connection.js:260:26)
	at CallbackList.invoke (/home/richardn/.vscode-oss/extensions/webfreak.code-d-0.23.2-universal/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/richardn/.vscode-oss/extensions/webfreak.code-d-0.23.2-universal/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/home/richardn/.vscode-oss/extensions/webfreak.code-d-0.23.2-universal/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/home/richardn/.vscode-oss/extensions/webfreak.code-d-0.23.2-universal/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:75:42)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:322:12)
```

**Comment by WebFreak001** [comment]
that's likely serve-d unable to start due to the most recent OpenSSL upgrade - check that `serve-d --version` works in the CLI

**Comment by Richardn2002** [comment]
Thanks for the quick response. Though actually off-topic, I just compiled `serve-d` from the latest release on GitHub myself and indeed it segfaults due to OpenSSL problems:

```
object.Exception@/home/richardn/.dub/packages/requests/2.1.1/requests/source/requests/ssl_adapter.d(204): loading openssl: unknown version Tuple!(int, "major", int, "minor")(3, 2) for init
```

For this issue, you can add some extra checks and hints to the user about debugger plugin statues, and then you can close it. Thank you again for your work on this project.

**Comment by WebFreak001** [comment]
for your OpenSSL issue: serve-d on master has been fixed, nightly being released shortly
