### ISSUE TITLE
visual studio code missing activation event

### ISSUE THREAD

**Issue by pirocks** [Pure-D/code-d#61]
When running visual studio code on debian, I get the following:
[http://imgur.com/pH5zjXg](url)
Opening the developer console I see the following stacktrace:
`[Extension Host] Here is the error stack:  Error: spawn EACCES`

    at exports._errnoException (util.js:890:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at Object.exports.spawn (child_process.js:379:9)
    at WorkspaceD.startWorkspaceD (/home/francis/.vscode/extensions/webfreak.code-d-0.10.13/out/src/workspace-d.js:76:38)
    at new WorkspaceD (/home/francis/.vscode/extensions/webfreak.code-d-0.10.13/out/src/workspace-d.js:68:14)
    at activate (/home/francis/.vscode/extensions/webfreak.code-d-0.10.13/out/src/extension.js:24:22)
    at Function.t._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:27785)
    at Function.t._callActivate (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:27568)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:11:27440
    at Object.m [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:9305)`

**Comment by WebFreak001** [comment]
is workspace-d an executable? It throws an EACCES error when trying to run workspace-d.

Check your vscode user settings and change the path to workspace-d to something where you are sure that its an executable that works. Right now it might be a directory instead of any executable.

**Comment by pirocks** [comment]
My bad. I provided the path to `/workspace-d/bin/workspace-d` instead of `workspace-d/workspace-d`
